# Generated by Django 2.2 on 2021-04-08 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_db_home_href'),
    ]

    operations = [
        migrations.CreateModel(
            name='DB_project_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, null=True)),
                ('remark', models.CharField(max_length=5000, null=True)),
                ('user', models.CharField(max_length=50, null=True)),
                ('other_user', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
