# Generated by Django 2.2 on 2021-07-04 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0004_auto_20210514_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_apis',
            name='body_method',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
